# Generated by Django 5.2 on 2026-09-08 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('technologies', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EXPERT_ASSIGNED', 'Expert Assigned'), ('EXPERT_APPROVED', 'Expert Approved'), ('COORDINATOR_APPROVED', 'Coordinator Approved'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_expert', models.ForeignKey(blank=True, limit_choices_to={'role': 'EXPERT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_proposals', to=settings.AUTH_USER_MODEL)),
                ('guide', models.ForeignKey(blank=True, limit_choices_to={'role': 'GUIDE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_proposals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
