# Generated by Django 5.2 on 2026-09-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectproposal_status_projectprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT_TO_STUDENT', 'Sent to Student'), ('RESUBMITTED', 'Resubmitted'), ('CLOSED', 'Closed')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_student_at', models.DateTimeField(blank=True, null=True)),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='expert_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='guide_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='guide_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EXPERT_ASSIGNED', 'Expert Assigned'), ('CHANGES_REQUESTED', 'Changes Requested'), ('EXPERT_APPROVED', 'Expert Approved'), ('COORDINATOR_APPROVED', 'Coordinator Approved'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('GUIDE_REJECTED', 'Guide Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='projectprogress',
            constraint=models.UniqueConstraint(fields=('project', 'week_number'), name='unique_project_week_progress'),
        ),
        migrations.AddField(
            model_name='proposalchangerequest',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COORDINATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalchangerequest',
            name='expert',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EXPERT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalchangerequest',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='projects.projectproposal'),
        ),
    ]
